# Numpy Task

### Instructions:
- Answer the following questions using NumPy only.
- Do not use Python loops unless explicitly stated.

## Part 1: Creating Arrays (3 Questions)


####  1) Create a NumPy array that contains all even numbers between 10 and 50 (inclusive).


In [1]:
import numpy as np

arr = np.arange(10,51,2)

print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]





#### 2) Create an array of shape (3, 4) filled with ones, then change all values in the last column to 0.



In [3]:
arr = np.ones(12).reshape(3,4)

arr[:,-1] = 0;

print(arr)

[[1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]]





#### 3) Create a NumPy array of 5 equally spaced numbers between -1 and 1.

In [4]:
arr = np.linspace(-1,1,5)

print(arr)

[-1.  -0.5  0.   0.5  1. ]


## Part 2: Array Properties (3 Questions)

#### 1) Create array and then
- Find its shape

- Number of elements

- Data type

In [10]:
arr = np.array([[2,3,4],[5,9,8]])
print(arr.shape)
print(arr.size)
print(arr.dtype)

(2, 3)
6
int64


#### 2) Create a random array of size 10 and find:
- minimum value

- maximum value

- standard deviation

In [13]:
arr = np.random.rand(10)

print(arr.max())
print(arr.min())
print(arr.std())

0.8103527655422337
0.006829195354560058
0.23116037098004524


#### 3) What is the difference between arr.size and arr.shape?

- Explain using an example.

1- arr.size

Total number of elements in the array.

2-arr.shape

Returns a tuple showing the dimensions of the array.


In [ ]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr.shape)
print(arr.size)


## Part 3: Mathematical Operations & ufuncs (3 Questions)

#### 1) Create a new array that contains the square of each element without using loops.

In [14]:
# Given

arr = np.array([1, 2, 3, 4, 5])

new_arr = arr ** 2

print(new_arr)


[ 1  4  9 16 25]


#### 2) Compute the mean and sum of all values in a 3×3 random matrix.

In [15]:
arr = np.random.rand(3,3)

print(arr.mean())
print(arr.sum())

0.40347846317769814
3.6313061685992833


#### 3) Compute the mean and sum of all values in a 3×3 random matrix.

In [16]:
arr = np.random.rand(3,3)

print(arr.mean())
print(arr.sum())

0.4834860799331299
4.351374719398169


## Part 4: Indexing, Slicing & Boolean Indexing (4 Questions)

#### 1) Extract the middle four elements using slicing.

In [17]:
# Given
arr = np.array([10, 20, 30, 40, 50, 60])

print(arr[1:5])


[20 30 40 50]


#### 2) From the same array, extract all values greater than 25.

In [18]:
print(arr[arr > 25])

[30 40 50 60]


#### 3) Modify the array so that all values less than 30 become 0.

In [19]:
arr[arr < 30] = 0

print(arr)

[ 0  0 30 40 50 60]



Slicing is better when:
- You know the exact positions or ranges you want
- You want a continuous block of data
- You care about order and fixed structure
- You need faster and simpler selection


Give one example.

-  Selecting the first 10 rows

In [ ]:
data = np.arange(100).reshape(20,5)  

first_10_rows = data[:10, :]

print(first_10_rows)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


## Part 5: Random Numbers & Performance (3 Questions)

#### 1) Generate a reproducible array of 15 random integers between 1 and 100.

In [20]:
arr = np.random.randint(1,101,15)

print(arr)

[14 74 67 77 32  3 51  1 26 39 77 60 41 19 35]


#### 2) Create two arrays:

- one using a Python loop

- one using NumPy vectorization

``to add 10 to each element.``

**Which one is faster and why?**

using NumPy vectorization bacuses it uses low level c language

In [21]:
lst = [1, 2, 3, 4, 5]
result = []

for x in lst:
    result.append(x + 10)

print(result)

[11, 12, 13, 14, 15]


In [22]:
arr = np.array([1,1,1])

print(arr + 10)

[11 11 11]


#### 4) Why is `np.random.seed()` important in data science experiments?

np.random.seed() ensures reproducible results by making random number generation consistent across multiple ru

## Part 6: Linear Algebra & Matrix Operations (2 Questions)

#### 1) Compute the determinant and inverse of a square matrix of your choice.

In [23]:
arr = np.array([[1,2],[3,4]])

print(np.linalg.det(arr))

print(np.linalg.inv(arr))

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


#### 2) What is the difference between:

- element-wise multiplication

- matrix multiplication
in NumPy?

Element-wise multiplication (*) multiplies each corresponding element of two arrays and requires them to have the same shape. Matrix multiplication (@ or np.dot()) follows linear algebra rules, multiplying rows by columns, and the shapes must be compatible, not necessarily identical

## Bonus (Optional – Mindset Question)

#### How does NumPy help a Data Analyst think in a vectorized and mathematical way instead of a procedural one?

NumPy allows operations on entire arrays at once, eliminating the need for explicit loops. This encourages a vectorized mindset, where you think in terms of whole datasets instead of individual elements. It also enables mathematical operations directly on arrays, making data analysis more efficient and scalable.